### ISSUE TITLE
Launching this repo

### ISSUE THREAD

**Issue by danielbachhuber** [danielbachhuber/pantheon-wordpress-develop#2]
- [x] Transfer to Pantheon organization
- [ ] Enable Circle on Pantheon organization to follow this project; set up appropriate env variables
- [ ] Create a new Pantheon user, and use their machine token in Circle config
- [ ] Post build status to Slack
- [ ] Trigger builds on a nightly basis somehow

**Comment by danielbachhuber** [comment]
@stevector Do you want to transfer the repo, make sure I still have access, and then set up Circle?

**Comment by stevector** [comment]
Yes, I'll do that now

**Comment by stevector** [comment]
In progress: https://github.com/pantheon-systems/pantheon-wordpress-develop

**Comment by danielbachhuber** [comment]
Closing in favor of https://github.com/pantheon-systems/pantheon-wordpress-develop/issues/1
